<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8D6Lswg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8D6Lswg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8D6Lswg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8D6Lswg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8D6Lswg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8D6Lswg',
    'container.build_id' => '985b0b8a',
    'container.build_time' => 1574999552,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8D6Lswg');
